Users - registration part1
huungry/cars_ptr pull request #8
Opened 2021-06-22 10:22 UTC by huungry

part 1 of registration users

2021-06-22 20:02 UTC, ptr97 reviewed
Ogolnie to idziesz w dobra strone ;) Mialem kilka uwag dotyczacych implementacji

2021-06-22 20:02 UTC, ptr97 commented on src/main/scala/com/hungry/cars/http/in/CreateUserRequest.scala
> +  def toUser: User = User(
Tutaj dopuszczasz do sytaucji ze moze zostac utworzona instancja User'a, ktora zawiera nieprawidlowe dane wewnatrz. Po to walidujesz wszystko, zeby miec pewnosc ze taka sytuacja nie bedzie miala miejsca nigdzie w code-base'ie. `Make illegal state unrepresentable ~ Debashish Ghosh (Functional and Reactive domain modeling)`

2021-06-27 20:27 UTC, ptr97 requested changes
Okej, jeszcze ogólne uwagi co do UserService'u. Sporo jest tam wymieszanych rzeczy z różnych poziomów logiki - są wysoko poziomowe deklaratywne rzeczy w stylu sprawdz czy user istnieje, ale tez sprawdzanie bardzo niskopoziomowo czy email jest wlasciwym emailem. Tworzy to sporo mess'u i zaciemnia logike biznesową. Wprowadzenie value class dla tych typów które tutaj walidujesz znacznie uprości całość. Składaj mniejsze klocki razem 😉

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/AppLauncher.scala
> +      val allRoutesCompleted: HttpApp[IO] = {
A może httpApp zamiast allRoutesCompleted? Ewentualnie zinline'ować? Bo to Completed mi tam srednio pasuje

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/domain/User.scala
> +  email: String,
Proponuje stworzyć value class'y na Email, Password, a nawet na Username

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/domain/error/UserError.scala
> +  case class UserAlreadyExists(userName: String) extends UserError {
1. Konwencja: username czy userName? 
2. Wszystkie te case class'y powinny byc final
3. Wszystkie property w tych case class'ach moga byc val'ami.
4. Ewentualnie: kody błędów można wynieść do jakiegoś private object'u

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/domain/error/UserError.scala
> +  case class EmailIsNotValid(email: String) extends UserError {
Nie powinno być wgl takiej możliwości invalid email powinien sfailowac na wejsciu do systemu przy deserializacji z JSONa. Czyli value class'a EmailAddress, która moża zawierać tylko i wyłącznie poprawny email.

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/domain/error/UserError.scala
> +  case class EmailAlreadyExists(email: String) extends UserError {
Czy to nie to samo co UserAlreadyExists?

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/domain/error/UserError.scala
> +  case object PasswordCanNotEncrypt extends UserError {
To nie jest błąd domenowy. Co uzytkownik Twojego API ma z tym zrobić? Ten case sygnalizuje blad programistyczny.

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/domain/error/UserError.scala
> +  case object AgeIsInvalid extends UserError {
To może tak samo - value class'a dla Age. Ewentualnie ogarnij coś takiego jak refined (https://github.com/fthomas/refined). Z tym, że sporo rzeczy stamtąd nie będziesz potrzebował.

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/domain/error/UserError.scala
> +  private def toJson(userError: UserError): Json = {
To jest okej, ale w razie czego istnieje taka biblioteka jak circe-tagged (https://index.scala-lang.org/abdolence/circe-tagged-adt-codec/circe-tagged-adt-codec/0.10.0?target=_3.x). Na razie to zostaw w ten sposób, ale warto wiedzieć o takiej bibliotece ;)

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/http/routes/UserRoutes.scala
> +      case req @ POST -> Root / "users" =>
Ten path sugeruje, że ktoś tworzy tych użytkowników. Może to powinno być "users" / "register"?

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/services/UserService.scala
> +        IO {
IO.pure -> tutaj juz zwracasz pure wartosc

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/services/UserService.scala
> +        IO {
IO.pure

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/domain/ValidatedCreateUserRequest.scala
> +case class ValidatedCreateUserRequest(
Nie widze sensu istnienia takiej case class'y. Moge bez problemu utworzyc obiekt takiej klasy ktory jest niepoprawny. Tak naprawde niczym sie to nie rozni od CreateUserRequest na poziomie typow.

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/services/UserService.scala
> +             case Left(_) => IO.pure(())
To tutaj nigdy nie zwrocisz error'a przez http

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/services/UserService.scala
> +      x: Either[NonEmptyChain[UserError], ValidatedCreateUserRequest] =
x to slaba nazwa 😉

2021-06-27 20:27 UTC, ptr97 commented on src/main/scala/com/hungry/cars/services/UserService.scala
> +  private def maybeEncryptPassword(password: String): Try[String] = password.bcryptSafeBounded
Rethrow'uj tego Failure'a do kontekstu IO - wtedy ta logika zwiazana z haslem sie uprosci, a blad domenowy PasswordCanNotEncrypt przestanie istniec.

2022-07-01 14:21 UTC, closed without merging

2022-07-01 14:24 UTC, ptr97 commented
Eee co jest? Na kiedy to bedzie zriobione?

2022-07-01 14:35 UTC, huungry commented
Mordo w następnym sprincie

W dniu pt., 1.07.2022 o 16:24 Piotr Woś ***@***.***>
napisał(a):

> Eee co jest? Na kiedy to bedzie zrobione?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/huungry/cars_ptr/pull/8#issuecomment-1172405679>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJCF2HUBSQYN3YM7QP4LU4LVR35RZANCNFSM47DMGACQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>